services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=simple_bank
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE="postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable"
    depends_on:
      - postgres
    links:
      - postgres